### ISSUE TITLE
Crash when pressing bound key

### ISSUE THREAD

**Issue by 533kr** [Gluton-Official/QuickSpyglasser#3]
Repeatable, happens every time regardless of which key is selected. Likely a mod incompatibility issue considering how many I have installed.

Crash log:
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/20/21, 5:30 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.class_1309.method_5998(class_1309.java:1893)
	at net.minecraft.class_1799.handler$zpl000$use(class_1799.java:2200)
	at net.minecraft.class_1799.method_7913(class_1799.java)
	at com.gluton.quickspyglasser.QuickSpyglasserClient.useSpyglass(QuickSpyglasserClient.java:64)
	at com.gluton.quickspyglasser.QuickSpyglasserClient.lambda$onInitializeClient$0(QuickSpyglasserClient.java:45)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bjf000$onEndTick(class_310.java:10073)
	at net.minecraft.class_310.method_1574(class_310.java:1808)
	at net.minecraft.class_310.method_1523(class_310.java:1083)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1309.method_5998(class_1309.java:1893)
	at net.minecraft.class_1799.handler$zpl000$use(class_1799.java:2200)
	at net.minecraft.class_1799.method_7913(class_1799.java)
	at com.gluton.quickspyglasser.QuickSpyglasserClient.useSpyglass(QuickSpyglasserClient.java:64)
	at com.gluton.quickspyglasser.QuickSpyglasserClient.lambda$onInitializeClient$0(QuickSpyglasserClient.java:45)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bjf000$onEndTick(class_310.java:10073)

-- Affected level --
Details:
	All players: 1 total; [class_746['s33kndestr0y'/51, l='ClientLevel', x=39.16, y=67.00, z=240.62]]
	Chunk stats: 256, 49
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,78,-16), Section: (at 0,14,0 in -7,4,-1; chunk contains blocks -112,0,-16 to -97,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1623922 game time, 18000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, LBPR+Reload!+v.4.6+for+mc1.16.zip, visual-leaf-decay-e1800.zip, guiretextures-1.6.4-1.17.zip, colourful-containers-dark-mode-e1650.zip, Lithos-Font+v11+for+1.17.1+.zip, enchanted-e1490.zip, vtb-nbv-dark-chromatic.zip, Dramatic+Skys+Demo+1.2+.zip

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 697535696 bytes (665 MiB) / 2013265920 bytes (1920 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18767.02
	Virtual memory used (MB): 11468.71
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 2.0.0+1.17
		apoli: Apoli 1.0.3
		autoswitch: AutoSwitch 3.2.2-alpha.1
		autoswitch-api: AutoSwitch API 1.0.0
		bedrockify: BedrockIfy 1.1.1+mc1.17
		blur: Blur (Fabric) 2.1.0
		calio: Calio 1.0.1
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		chat_heads: Chat Heads 0.3+1.17
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynamicfps: Dynamic FPS 2.0.4
		editsign: EditSign 2.2.1
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fancymenu: FancyMenu 2.1.2
		ferritecore: FerriteCore 3.0.1
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.6
		invisframes: Invisible Frames 2.0.2
		iris: Iris 1.1.0+rev.f06a69d
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.8.7-1.17
		konkrete: Konkrete 1.2.1
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		minecraft: Minecraft 1.17
		modmenu: Mod Menu 2.0.2
		notes: Notes 1.0.6
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		particlerain: Particle Rain 1.3.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		puddles: Puddles 1.1.0
		quickspyglasser: Quick Spyglasser 0.2.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		rhino: Rhino 1605.1.1-build.23
		satin: Satin 1.6.0-nightly.1.17-pre3
		sodium: Sodium 0.3.0+IRIS1-rev.7491e3a
		spark: spark ${pluginVersion}
		spruceui: SpruceUI 3.2.0+1.17
		spyzoom: Spyglass Zoom 1.0.1
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		voicechat: Simple Voice Chat 1.17-1.1.5
		xaerominimap: Xaero's Minimap 21.13.0
		xaeroworldmap: Xaero's World Map 1.14.6.1
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/LBPR+Reload!+v.4.6+for+mc1.16.zip (incompatible), file/visual-leaf-decay-e1800.zip, file/guiretextures-1.6.4-1.17.zip, file/colourful-containers-dark-mode-e1650.zip (incompatible), file/Lithos-Font+v11+for+1.17.1+.zip, file/enchanted-e1490.zip (incompatible), file/vtb-nbv-dark-chromatic.zip (incompatible), file/Dramatic+Skys+Demo+1.2+.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
	Player Count: 1 / 8; [class_3222['s33kndestr0y'/51, l='ServerLevel[Workshop]', x=39.16, y=67.00, z=240.62]]
	Data Packs: vanilla (incompatible), Fabric Mods
```

**Comment by Gluton-Official** [comment]
Thank you! I will look into it

**Comment by Gluton-Official** [comment]
Completed with 68f263f88ac56caee6d80407eaf84a99531f1faa

[CurseForge download available](https://www.curseforge.com/minecraft/mc-mods/quick-spyglasser/files/3408233)
